name: Android CD

on:
  push:
    tags:
      - v*

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode BASEURL
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: echo API_BASE_URL=$API_BASE_URL > ./local.properties
      - name: Unit tests
        run: ./gradlew test --stacktrace

  android_tests:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode BASEURL
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: echo API_BASE_URL=$API_BASE_URL > ./local.properties
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-build: 7425822
          script: ./gradlew connectedCheck --stacktrace

  build:
    needs: [ unit_tests, android_tests ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Decode BASEURL
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
      run: echo API_BASE_URL=$API_BASE_URL > ./local.properties
#    - name: Decode Keystore
#      id: decode_keystore
#      uses: timheuer/base64-to-file@v1
#      with:
#        fileDir: '/app/keystore'
#        fileName: 'NarutoKeyStore.jks'
#        encodedString: ${{ secrets.KEYSTORE }}
    - name: Build Release Artifact
      run: ./gradlew app:assembleRelease --stacktrace
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Release Artifacts
        path: app/build/outputs/apk/release/*.apk
    - name: Release Artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/outputs/apk/release/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
